from datetime import datetime
import os, string, random, smtplib, ssl, csv

def createDateTimeObject(time):
    year = time[:4]
    month = time[5:7]
    day = time[8:10]

    time = time[11:]

    time = f"{day}/{month}/{year[2:]} " + time

    return datetime.strptime(time + ":00", '%d/%m/%y %H:%M:%S')

# send email
def send_email(TOKEN, receiver, validationForm = True):
    port = 465  # For SSL
    password = "Wasd123!"
    sender_email = "GamerIO5500@gmail.com"
    if validationForm:
        message = f"""\
        Validate Email

        This message is sent from GamerIO.
        
        Your code is: {TOKEN}

        You can authenticate your code here: http://124.176.55.35:5500/user/authenticate/
        
        This email is generated by GamerIO, made by Zachary Lo. Don't worry I'm not gonna give you virus.
        """

    else:
        message = f"""\
        Test Email

        Let's see if this link will work
        
        You can authenticate your code here: http://124.176.55.35:5500/user/user-id/{TOKEN}
        
        This email is generated by GamerIO, made by Zachary Lo. Don't worry I'm not gonna give you virus.
        """

    # Create a secure SSL context
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", port, context=context) as server:
        server.login("GamerIO5500@gmail.com", password)
        server.sendmail(sender_email, receiver, message)